parameters:
#    buzzwoo_yo.example.class: Buzzwoo\YoBundle\Example

services:
#    buzzwoo_yo.example:
#        class: %buzzwoo_yo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
